services:
  discord-bot:
    build: ./apps/discord-bot
    env_file:
      - ./apps/discord-bot/.env
  website:
    build: ./apps/website
    env_file:
      - ./apps/website/.env
    ports:
      - "80:5050"
  websocket-skyblock:
    build: ./apps/websocket-skyblock
    env_file:
      - ./apps/websocket-skyblock/.env
    ports:
      - "3001:3001"
  nginx:
    build: ./apps/nginx
    network_mode: host
    ports:
      - "3000:80"
    volumes:
      - ./apps/nginx.conf:/etc/nginx/nginx.conf