services:
  discord-bot:
    build: ./apps/discord-bot
    env_file:
      - ./apps/discord-bot/.env
  website:
    build: ./apps/website
    env_file:
      - ./apps/website/.env
    ports:
      - "80:5050"
  websocket-skyblock:
    build: ./apps/websocket-skyblock
    env_file:
      - ./apps/websocket-skyblock/.env
    ports:
      - "3001:3000"
  nginx:
    build: ./apps/nginx
    container_name: ${NGINX_HOST}
    env_file:
      - ./apps/nginx/.env
    image: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    restart: always