services:
  discord-bot:
    build: ./apps/discord-bot
    env_file:
      - ./apps/discord-bot/.env
  website:
    build: ./apps/website
    env_file:
      - ./apps/website/.env
    ports:
      - "80:5050"
  websocket-skyblock:
    build: ./apps/websocket-skyblock
    env_file:
      - ./apps/websocket-skyblock/.env
    ports:
      - "3001:3000"
  nginx-server:
    build: ./apps/nginx-server
    env_file:
      - ./apps/nginx/.env
    ports:
      - "${NGINX_PORT}:3001"