declare CONTENT
INFORMATION="# Generated by 'gradle build' from script file 'prebuild.sh', receives .env from '../.env'. Created because I'm too lazy to copy .envs forward and back"

> .env
echo "$INFORMATION" >> .env
echo "" >> .env

for LINE in $(cat ../.env)
do
    echo "$LINE" >> .env
done

# echo $CONTENT