import { config } from "dotenv";
config();

/**
 * Holds our environment variables
 */
export const BotEnvironment = {
	ADMIN_1: process.env.ADMIN_1!,
	ADMIN_2: process.env.ADMIN_2!,
	DISCORD_APPLICATION_ID: process.env.DISCORD_APPLICATION_ID!,
	DISCORD_MAIN_CHANNEL_ID: process.env.DISCORD_MAIN_CHANNEL_ID!,
	DISCORD_PUBLIC_KEY: process.env.DISCORD_PUBLIC_KEY!,
	DISCORD_SEND_CHANNEL_ID: process.env.DISCORD_SEND_CHANNEL_ID!,
	DISCORD_TOKEN: process.env.DISCORD_TOKEN!,
	HYPIXEL_BOT_KEY: process.env.HYPIXEL_BOT_KEY!,
	MONGODB_USERNAME: process.env.MONGODB_USERNAME!,
	MONGODB_PASSWORD: process.env.MONGODB_PASSWORD!,
	MONGODB_DATABASE_NAME: process.env.MONGODB_DATABASE_NAME!,
	MONGODB_COLLECTION_BAZAAR_ITEMS_NAME: process.env.MONGODB_COLLECTION_BAZAAR_ITEMS_NAME!,
	MONGODB_COLLECTION_AUCTION_ITEMS_NAME: process.env.MONGODB_COLLECTION_AUCTION_ITEMS_NAME!,
} as const;
